---
- name: copy file from one file to another
  hosts: localhost
  tasks:
  - name: copy file from /root/ansible.txt to /home/ec2-user/aws
    ansible.builtin.copy:
      src: /root/ansible.txt
      dest: /home/ec2-user/aws/ansible.txt