---
- name: Install LAMP in Amazon Linux server
  hosts: localhost
  become: yes

  tasks:
    # Install httpd
    - name: Install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: present

    # Install MariaDB
    - name: Install MariaDB package
      ansible.builtin.dnf:
        name: mariadb105-server
        state: present

    # Install PHP
    - name: Install PHP packages
      ansible.builtin.dnf:
        name:
          - php
          - php-fpm
        state: present

    # Start httpd
    - name: Start and enable httpd
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    # Start MariaDB
    - name: Start and enable MariaDB
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: true

    # Start PHP-FPM
    - name: Start and enable PHP-FPM
      ansible.builtin.systemd:
        name: php-fpm
        state: started
        enabled: true

    # Deploy PHP info page
    - name: Deploy PHP info page
      ansible.builtin.copy:
        dest: /var/www/html/index.php
        content: 
          <?php
          phpinfo();
          ?>
